Made functions members of respective classes rather than passing references to object of class
mgastner/cartogram-cpp pull request #125
Opened 2022-03-10 15:58 UTC by adisidev

This pull request relies on #117, as I changed the kernel for this pull request too. Thus, it may be a good idea to check that out first. This addresses multiple issues, which I shall list out shortly.

2022-03-13 14:33 UTC, mgastner requested changes
This pull request looks very nice. I only have a few comments and changes for requests. Please see my comments in the code.

2022-03-18 10:25 UTC, adisidev commented on src/inset_state/albers_projection.cpp
> +  // Specialise point_after_albers_projection with lx_ and ly_
I've changed the comment, and added the word `curry` as in https://en.wikipedia.org/wiki/Currying

More can be found here, upon searching the keyword "specialize": https://dev.realworldocaml.org/variables-and-functions.html

2022-03-18 10:27 UTC, adisidev commented on src/inset_state/project.cpp
> +  // Specialise interpolate_point_bilinearly
Same as the comment about the word specialise earlier.

2022-03-18 10:29 UTC, adisidev commented on src/inset_state/project.cpp
> +          coords_hole = projected_point_with_triangulation(coords_hole);
Indeed, it very much could be; I've changed it as suggested, thanks for point it out.

2022-03-18 10:38 UTC, adisidev commented on src/inset_state/project.cpp
> +          coords_hole = projected_point_with_triangulation(coords_hole);
Alas, I realise why I did not do it initially. After some more research, I was able to implement it as requested and reduce the unnecessary code-duplication.

2022-03-18 10:44 UTC, adisidev commented on src/inset_state/rescale_map.cpp
> +  // Ensure that the grid dimensions lx and ly are integer powers of 2
I'm unsure whether we should remove them or not. I have shifted `unsigned int lx, ly;` closer to the comment. Indeed, the next few lines do deal with setting appropriate `lx` and `ly`.  However, I do understand your concern too. So I shall leave it up to you to decide later.

2022-03-18 10:45 UTC, adisidev commented on src/inset_state/rescale_map.cpp
> +  // Ensure that the grid dimensions lx and ly are integer powers of 2
Instead, we could also round up to the nearest power of 2. However, doing this implicitly may confuse users why their sizes were changed.

2022-03-18 10:57 UTC, adisidev commented
Lots of functions are now unused. We should decide whether to keep them or not. I will create a commit removing them, and we can revert the commit if we feel it is best to retain the unused functions.

2022-03-27 07:22 UTC, mgastner approved these changes
Thank you for sorting the files. I also like the lambda-function approach to transforming points in `albers_projection.cpp`, `project.cpp` and `smyth_projection.cpp`. We should slowly roll out this technique broadly in similar cases.

2022-03-27 07:22 UTC, merged