Generate Cartogram using Quadtree-Delaunay Triangulation or qtdt Method
mgastner/cartogram-cpp pull request #134
Opened 2022-06-16 11:39 UTC by nihalzp

./bin/cartogram ./sample_data/belgium/belgium.geojson ./sample_data/belgium/belgium_population2019.csv -Q

2022-06-19 13:02 UTC, mgastner requested changes
Excellent job! Apart from minor remarks on code comments and variable names, there are two main issues:
- The projection only needs to be pushed back into proj_sequence at the very end of flatten_density(). 
- The grading of the quadtree needs to be turned on. 

I also left a comment about avoiding double-counting of polygon vertices on shared boundaries.

2022-06-24 20:51 UTC, mgastner requested changes
When I run `cartogram sample_data/bahamas/bahamas.geojson sample_data/bahamas/bahamas_population2010.csv -pQs`, the following polygon is invalid, apparently because the final point is repeated three times, and then the code exits with an error:

```
303.627 212.143
303.296 211.821
303.641 212.029
303.786 211.997
303.874 212.111
303.874 212.111
303.874 212.111
```

Can you please check whether the new densification code produces repeated points? As an indicator, you can check whether the polygon is simple. It is a strict requirement for CGAL's simplification to work.

2022-07-05 06:43 UTC, mgastner reviewed
I believe the variable `found_both_faces` is unnecessary. I also would like some clarification about finding a minimum in parallel. For me as a noobie to omp, it looks as if the omp-for-loop in `InsetState::bbox()` causes a "data race".

2022-07-05 07:13 UTC, nihalzp commented on src/inset_state/inset_state.cpp
> +#pragma omp parallel for
Good observation. It could indeed lead to race conditions. I have used reduction to avoid it.

2022-07-08 19:46 UTC, mgastner commented
The innovations from this pull request were moved into another pull request #140. That pull request was merged into main.

2022-07-08 19:46 UTC, closed without merging